[tool.mypy]
ignore_missing_imports = true
no_implicit_optional = true
plugins = [
]
show_error_codes = true
warn_unreachable = true
disable_error_code = "annotation-unchecked"

[tool.ruff]
target-version = "py310"
line-length = 99

[tool.ruff.lint]
select = [
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
  "D",  # pydocstyle
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "W",  # pycodestyle warnings
]
ignore = []
extend-ignore = [
    "E731", # do not assign a lambda expression, use a def
    "E203", # whitespace before ':'
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
